In [2]:
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt 

import seaborn as sns

With Pandas we can read the csv we just made in 1, or pass alink to the raw content

In [7]:
data = pd.read_csv("https://raw.githubusercontent.com/Zipcoder/DataEngineering.Labs.Libraries/master/Pandas%20-%20Part%201%20(importing%20data%2C%20summary%20stats)/\
Combined%20Wine%20Data.csv?token=ALOLXOLFRIDBG2N4OHH2NIK6HNDGY")

In [8]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

### Rearranging the dataFrame for ease of use:
Extract list of columns, reaarnge, construct a new df with custom order.

In [9]:
columns = data.columns.to_list()
columns

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality',
 'color']

In [10]:
columns.sort()
columns

['alcohol',
 'chlorides',
 'citric acid',
 'color',
 'density',
 'fixed acidity',
 'free sulfur dioxide',
 'pH',
 'quality',
 'residual sugar',
 'sulphates',
 'total sulfur dioxide',
 'volatile acidity']

In [11]:
columns.insert(0, columns.pop(columns.index('color')))

In [12]:
columns

['color',
 'alcohol',
 'chlorides',
 'citric acid',
 'density',
 'fixed acidity',
 'free sulfur dioxide',
 'pH',
 'quality',
 'residual sugar',
 'sulphates',
 'total sulfur dioxide',
 'volatile acidity']

In [13]:
rearranged_data = data[columns]
rearranged_data.head()

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
0,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70
1,red,9.8,0.098,0.00,0.9968,7.8,25.0,3.20,5,2.6,0.68,67.0,0.88
2,red,9.8,0.092,0.04,0.9970,7.8,15.0,3.26,5,2.3,0.65,54.0,0.76
3,red,9.8,0.075,0.56,0.9980,11.2,17.0,3.16,6,1.9,0.58,60.0,0.28
4,red,9.4,0.076,0.00,0.9978,7.4,11.0,3.51,5,1.9,0.56,34.0,0.70

### Creating this view did NOT create a new data frame. 
The above just shows the original data in our desired column order. To prove it:

In [15]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

### Slicing

In [16]:
rearranged_data['residual sugar'].mean()

5.443235339387409

In [17]:
high_sugar_wines = rearranged_data[rearranged_data['residual sugar'] > rearranged_data['residual sugar'].mean()]

In [18]:
high_sugar_wines.color.value_counts()

color
white    2383
red        74
Name: count, dtype: int64

In [20]:
high_sugar_wines= high_sugar_wines[high_sugar_wines.color !='white']

In [21]:
high_sugar_wines.head()

,color,alcohol,chlorides,citric acid,density,fixed acidity,free sulfur dioxide,pH,quality,residual sugar,sulphates,total sulfur dioxide,volatile acidity
9,red,10.5,0.071,0.36,0.9978,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
11,red,10.5,0.071,0.36,0.9978,7.5,17.0,3.35,5,6.1,0.80,102.0,0.500
33,red,9.4,0.073,0.12,0.9993,6.9,40.0,3.45,6,10.7,0.52,83.0,0.605
35,red,9.6,0.086,0.00,0.9986,7.8,5.0,3.40,6,5.5,0.55,18.0,0.645
39,red,10.5,0.074,0.36,0.9978,7.3,12.0,3.33,5,5.9,0.83,87.0,0.450